/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Model;

import ADO.Empresa;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Rhian
 */
public class InfoEmpresa extends javax.swing.JDialog {

    /**
     * Creates new form InfoEmpresa2
     */
    private  List<Empresa> listaEmpresa = new ArrayList<>();
    /**
     * Creates new form InfoEmpresa
     */
    void atualizar(){
        listaEmpresa.forEach(empre ->{
            tfNomeEmpresa.setText(empre.getNome());
            tfBairro.setText(empre.getBairro());
            tfCep.setText(empre.getCep());
            tfCidade.setText(empre.getCidade());
            tfCnpj.setText(empre.getCnpj());
            tfNum.setText(empre.getNumero());
            tfPais.setText(empre.getPais());
            tfRepresentante.setText(empre.getRepresentante());
            tfRua.setText(empre.getRua());
            tfUf.setText(empre.getEstado());
            tfTelefone.setText(empre.getTelefone());
        
        });
        
    
    }

      
        

    
    public InfoEmpresa(java.awt.Frame parent, boolean modal,List<Empresa>lista) {
        super(parent, modal);
        initComponents();
        this.listaEmpresa = lista;
        atualizar();
        setTitle("Informações da Empresa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfNomeEmpresa = new javax.swing.JTextField();
        tfCnpj = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfRepresentante = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JTextField();
        tfUf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfCep = new javax.swing.JTextField();
        tfCidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfRua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfBairro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfPais = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfNum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(30, 39, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfNomeEmpresa.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tfNomeEmpresa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 203, 110), 2));
        jPanel1.add(tfNomeEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 230, -1));

        tfCnpj.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tfCnpj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 203, 110), 2));
        jPanel1.add(tfCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 230, -1));

        jLabel12.setForeground(new java.awt.Color(236, 240, 241));
        jLabel12.setText("CNPJ:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabel11.setForeground(new java.awt.Color(236, 240, 241));
        jLabel11.setText("Nome da Empresa:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 240, 241));
        jLabel1.setText("Informações:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        tfRepresentante.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tfRepresentante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 203, 110), 2));
        jPanel1.add(tfRepresentante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 230, -1));

        jLabel10.setForeground(new java.awt.Color(236, 240, 241));
        jLabel10.setText("Representante:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel13.setForeground(new java.awt.Color(236, 240, 241));
        jLabel13.setText("Telefone:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        tfTelefone.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tfTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 203, 110), 2));
        jPanel1.add(tfTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 230, -1));

        tfUf.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tfUf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 203, 110), 2));
        jPanel1.add(tfUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 60, -1));

        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("UF:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, -1));

        jLabel9.setForeground(new java.awt.Color(236, 240, 241));
        jLabel9.setText("CEP:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 240, 241));
        jLabel2.setText("Endereço:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        tfCep.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tfCep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 203, 110), 2));
        jPanel1.add(tfCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 120, -1));

        tfCidade.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tfCidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 203, 110), 2));
        jPanel1.add(tfCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 260, -1));

        jLabel3.setForeground(new java.awt.Color(236, 240, 241));
        jLabel3.setText("Cidade:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        tfRua.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tfRua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 203, 110), 2));
        jPanel1.add(tfRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 260, -1));

        jLabel7.setForeground(new java.awt.Color(236, 240, 241));
        jLabel7.setText("Rua:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        tfBairro.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tfBairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 203, 110), 2));
        jPanel1.add(tfBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 120, -1));

        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("Bairro:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("País:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        tfPais.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tfPais.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 203, 110), 2));
        jPanel1.add(tfPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 120, -1));

        jButton1.setBackground(new java.awt.Color(253, 203, 110));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 50, 50));

        jButton2.setBackground(new java.awt.Color(253, 203, 110));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voltarIcon.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 50));

        jLabel8.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8.setText("Num.:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        tfNum.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tfNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 203, 110), 2));
        jPanel1.add(tfNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 60, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfCep;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfCnpj;
    private javax.swing.JTextField tfNomeEmpresa;
    private javax.swing.JTextField tfNum;
    private javax.swing.JTextField tfPais;
    private javax.swing.JTextField tfRepresentante;
    private javax.swing.JTextField tfRua;
    private javax.swing.JTextField tfTelefone;
    private javax.swing.JTextField tfUf;
    // End of variables declaration//GEN-END:variables
}
